// Auto-generated by scan_drive.py — DO NOT EDIT
const STUDENT_DATA = {
  "9a1": {
    "Mai Gia Huy": [
      {
        "thumb": "https://lh3.googleusercontent.com/d/1ybFEjsjn0J3GGYRM-Dz8OliNtSppqumG=w600",
        "view": "https://lh3.googleusercontent.com/d/1ybFEjsjn0J3GGYRM-Dz8OliNtSppqumG=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1qKc2uQI3wKabBIgYHkAu9jAbQP1xqok6=w600",
        "view": "https://lh3.googleusercontent.com/d/1qKc2uQI3wKabBIgYHkAu9jAbQP1xqok6=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1SEi8PHpN_W9jwsM6cNxQkpC2d8pyfTBK=w600",
        "view": "https://lh3.googleusercontent.com/d/1SEi8PHpN_W9jwsM6cNxQkpC2d8pyfTBK=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1LfzykrGLifsEH77JA_YvkE6UEYXiuauI=w600",
        "view": "https://lh3.googleusercontent.com/d/1LfzykrGLifsEH77JA_YvkE6UEYXiuauI=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1D-ZFXs99T7bT9UjVDNcXVLryAs3L3PRA=w600",
        "view": "https://lh3.googleusercontent.com/d/1D-ZFXs99T7bT9UjVDNcXVLryAs3L3PRA=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1orb8yaaRhI4Yk0PJC_6mdsFxR-CDlpJY=w600",
        "view": "https://lh3.googleusercontent.com/d/1orb8yaaRhI4Yk0PJC_6mdsFxR-CDlpJY=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/123Px_eCYW-9_m_5w-002GKwUlUZYL6cQ=w600",
        "view": "https://lh3.googleusercontent.com/d/123Px_eCYW-9_m_5w-002GKwUlUZYL6cQ=w1600"
      }
    ]
  },
  "9a2": {
    "nguyễn yến linh": [
      {
        "thumb": "https://lh3.googleusercontent.com/d/1hXYHQmtfDHBqb5vVzaQP4CQR4jL7UlMQ=w600",
        "view": "https://lh3.googleusercontent.com/d/1hXYHQmtfDHBqb5vVzaQP4CQR4jL7UlMQ=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1MHA139lszCawmRYR6lms3fzeJtsoOMg2=w600",
        "view": "https://lh3.googleusercontent.com/d/1MHA139lszCawmRYR6lms3fzeJtsoOMg2=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1j32xIHRZZTycBZFfMwyuXnqdOOpuvrq8=w600",
        "view": "https://lh3.googleusercontent.com/d/1j32xIHRZZTycBZFfMwyuXnqdOOpuvrq8=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1F94X1Hbm3RCfb6xTACcVsM9EYkrgh23j=w600",
        "view": "https://lh3.googleusercontent.com/d/1F94X1Hbm3RCfb6xTACcVsM9EYkrgh23j=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1FDqjYm58yHS9nIGEaJuy24SRWOZjLmQF=w600",
        "view": "https://lh3.googleusercontent.com/d/1FDqjYm58yHS9nIGEaJuy24SRWOZjLmQF=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1M4oSP9O8ZeE0T9jipxUaovqckWv784-s=w600",
        "view": "https://lh3.googleusercontent.com/d/1M4oSP9O8ZeE0T9jipxUaovqckWv784-s=w1600"
      }
    ]
  },
  "9a3": {
    "Mai Hà Trang": [
      {
        "thumb": "https://lh3.googleusercontent.com/d/1j4OLtoRLuFO8rfqf5idjxWgr2Pt643mS=w600",
        "view": "https://lh3.googleusercontent.com/d/1j4OLtoRLuFO8rfqf5idjxWgr2Pt643mS=w1600"
      },
      {
        "thumb": "https://lh3.googleusercontent.com/d/1__lGiv2fYljLOV7wMUtLRdu35DTSTgVm=w600",
        "view": "https://lh3.googleusercontent.com/d/1__lGiv2fYljLOV7wMUtLRdu35DTSTgVm=w1600"
      }
    ]
  }
};
