"""
scan_drive.py
-------------
Đọc Google Sheet (class | student_name | drive_folder_id)
Với mỗi học sinh, quét folder Google Drive để lấy tất cả ảnh
Xuất ra js/data.js dùng cho website yearbook
"""

import os
import json
import sys
import re
import requests

# Fix Unicode output on Windows
sys.stdout.reconfigure(encoding='utf-8')

# ─── Load .env ───────────────────────────────────────────────────
def load_env(path='.env'):
    env = {}
    with open(path, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            m = re.match(r'^([A-Z_]+)\s*=\s*["\']?([^"\']+)["\']?\s*$', line)
            if m:
                env[m.group(1)] = m.group(2).strip()
    return env

env = load_env()
API_KEY  = env.get('GOOGLE_API_KEY', '')
SHEET_ID = env.get('SHEET_ID', '')

if not API_KEY or not SHEET_ID:
    print("ERROR: Thiếu GOOGLE_API_KEY hoặc SHEET_ID trong .env")
    sys.exit(1)

# ─── Helper: Đọc Google Sheet dưới dạng CSV ──────────────────────
def read_sheet(sheet_id):
    url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    r.encoding = 'utf-8'  # Force UTF-8 regardless of Content-Type header

    import csv, io
    reader = csv.DictReader(io.StringIO(r.text))
    rows = []
    for row in reader:
        rows.append({k.strip().lower(): v.strip() for k, v in row.items()})
    return rows

# ─── Helper: Liệt kê ảnh trong 1 folder Drive ────────────────────
IMAGE_MIME = ('image/jpeg', 'image/png', 'image/webp', 'image/gif')

def list_images_in_folder(folder_id):
    """Trả về list dict {thumb, view} của các ảnh trong folder Drive (public)."""
    q = f"'{folder_id}' in parents and trashed=false"
    fields = "files(id,name,mimeType)"
    url = (
        "https://www.googleapis.com/drive/v3/files"
        f"?q={requests.utils.quote(q)}&fields={fields}"
        f"&key={API_KEY}&pageSize=200&orderBy=name"
    )
    r = requests.get(url, timeout=30)
    if r.status_code != 200:
        print(f"  ⚠️  Lỗi khi đọc folder {folder_id}: {r.status_code} {r.text[:200]}")
        return []
    files = r.json().get('files', [])
    images = []
    for f in files:
        if f.get('mimeType', '') in IMAGE_MIME:
            fid = f['id']
            images.append({
                # thumbnail cho lưới ảnh
                "thumb": f"https://lh3.googleusercontent.com/d/{fid}=w600",
                # full res cho lightbox (CDN, không bị chặn)
                "view":  f"https://lh3.googleusercontent.com/d/{fid}=w1600"
            })
    return images

# ─── Main: Build STUDENT_DATA ─────────────────────────────────────
def main():
    print(f"Đọc Google Sheet: {SHEET_ID}")
    rows = read_sheet(SHEET_ID)
    if not rows:
        return

    # Kiểm tra header
    required = {'class', 'student_name', 'drive_folder_id'}
    headers_found = set(rows[0].keys())
    if not required.issubset(headers_found):
        print(f"ERROR: Sheet thiếu cột. Cần có: {required}")
        print(f"Sheet hiện có: {headers_found}")
        sys.exit(1)

    data = {}
    for row in rows:
        cls         = row['class'].strip().lower()
        student     = row['student_name'].strip()
        folder_id   = row['drive_folder_id'].strip()

        if not cls or not student or not folder_id:
            continue

        if cls not in data:
            data[cls] = {}

        print(f"  Quét [{cls}] {student} (folder: {folder_id[:20]}...)")
        images = list_images_in_folder(folder_id)
        print(f"    → {len(images)} ảnh")

        if student not in data[cls]:
            data[cls][student] = []
        data[cls][student].extend(images)

    # Xuất data.js
    os.makedirs('js', exist_ok=True)
    with open('js/data.js', 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by scan_drive.py — DO NOT EDIT\n')
        f.write('const STUDENT_DATA = ')
        f.write(json.dumps(data, indent=2, ensure_ascii=False))
        f.write(';\n')

    total_students = sum(len(v) for v in data.values())
    total_photos   = sum(len(imgs) for cls in data.values() for imgs in cls.values())
    print(f"\n✅ Xuất js/data.js: {len(data)} lớp | {total_students} học sinh | {total_photos} ảnh")

if __name__ == '__main__':
    main()
